export const ADD_TABLE_RESERVATIONS = 'ADD_TABLE_RESERVATIONS';
export const DELETE_TABLE_RESERVATIONS = 'DELETE_TABLE_RESERVATIONS';
export const UPDATE_TABLE_RESERVATIONS = 'UPDATE_TABLE_RESERVATIONS';
export const FETCH_TABLE_RESERVATIONS = 'FETCH_TABLE_RESERVATIONS';
export const UPDATE_ONE = 'UPDATE_ONE';
export const ON_CHANGE_TABLE_RESERVATIONS = 'ON_CHANGE_TABLE_RESERVATIONS';
export const ON_CHANGE_SLIDER = 'ON_CHANGE_SLIDER';
