export const ADD_CHAMBRES = 'ADD_CHAMBRES';
export const DELETE_CHAMBRES = 'DELETE_CHAMBRES';
export const UPDATE_CHAMBRES = 'UPDATE_CHAMBRES';
export const FETCH_CHAMBRES = 'FETCH_CHAMBRES';
export const UPDATE_ONE = 'UPDATE_ONE';
export const ON_CHANGE_CHAMBRES = 'ON_CHANGE_CHAMBRES';
export const ON_CHANGE_SLIDER = 'ON_CHANGE_SLIDER';
export const NEW_DATA_CHAMBRES = 'NEW_DATA_CHAMBRES';