export const ADD_RESPONSABLES = 'ADD_RESPONSABLES';
export const FETCH_RESPONSABLES = 'FETCH_RESPONSABLES';
export const UPDATE_EROOR = 'UPDATE_EROOR';
export const USER_CONNECTER = 'USER_CONNECTER';
export const DELETE_RESPONSABLES = 'DELETE_RESPONSABLES';
export const UPDATE_RESPONSABLES = 'UPDATE_RESPONSABLES';
