export const ADD_TABLE_CLIENTS = 'ADD_TABLE_CLIENTS';
export const DELETE_TABLE_CLIENTS = 'DELETE_TABLE_CLIENTS';
export const UPDATE_TABLE_CLIENTS = 'UPDATE_TABLE_CLIENTS';
export const FETCH_TABLE_CLIENTS = 'FETCH_TABLE_CLIENTS';
export const UPDATE_ONE = 'UPDATE_ONE';
export const ON_CHANGE_TABLE_CLIENTS = 'ON_CHANGE_TABLE_CLIENTS';
export const ON_CHANGE_SLIDER = 'ON_CHANGE_SLIDER';
